name: Test Workflow

on:
  push:
    branches:
      - DEV

jobs:
  quick-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DEV
        uses: actions/checkout@v3

      - name: Quick Test
        run: |
          echo "This is a dummy test."
          echo "Workflow ran successfully!"
